const products = [
  // ---------------- GROCERY ----------------
  {
    id: 1,
    name: "Fresh Red Apple",
    category: "grocery",
    subCategory: "Fruits",
    price: 120,
    rating: 4.5,
    emoji: "🍎",
    stock: true,
  },
  {
    id: 2,
    name: "Fresh Banana",
    category: "grocery",
    subCategory: "Fruits",
    price: 60,
    rating: 4.3,
    emoji: "🍌",
    stock: true,
  },
  {
    id: 3,
    name: "Fresh Broccoli",
    category: "grocery",
    subCategory: "Vegetables",
    price: 90,
    rating: 4.4,
    emoji: "🥦",
    stock: true,
  },
  {
    id: 4,
    name: "Fresh Carrot",
    category: "grocery",
    subCategory: "Vegetables",
    price: 70,
    rating: 4.2,
    emoji: "🥕",
    stock: true,
  },
  {
    id: 5,
    name: "Potato Chips",
    category: "grocery",
    subCategory: "Snacks",
    price: 40,
    rating: 4.1,
    emoji: "🍿",
    stock: true,
  },
  {
    id: 6,
    name: "Orange Juice",
    category: "grocery",
    subCategory: "Beverages",
    price: 110,
    rating: 4.6,
    emoji: "🧃",
    stock: false,
  },

  // ---------------- FASHION ----------------
  {
    id: 7,
    name: "Classic T-Shirt",
    category: "fashion",
    subCategory: "Men",
    price: 599,
    rating: 4.3,
    emoji: "👕",
    stock: true,
  },
  {
    id: 8,
    name: "Blue Jeans",
    category: "fashion",
    subCategory: "Men",
    price: 1299,
    rating: 4.5,
    emoji: "👖",
    stock: true,
  },
  {
    id: 9,
    name: "Women's Dress",
    category: "fashion",
    subCategory: "Women",
    price: 1499,
    rating: 4.6,
    emoji: "👗",
    stock: true,
  },
  {
    id: 10,
    name: "Running Shoes",
    category: "fashion",
    subCategory: "Shoes",
    price: 1999,
    rating: 4.4,
    emoji: "👟",
    stock: true,
  },
  {
    id: 11,
    name: "Leather Handbag",
    category: "fashion",
    subCategory: "Bags",
    price: 1799,
    rating: 4.2,
    emoji: "👜",
    stock: false,
  },
  {
    id: 12,
    name: "Sunglasses",
    category: "fashion",
    subCategory: "Accessories",
    price: 799,
    rating: 4.1,
    emoji: "🕶️",
    stock: true,
  },

  // ---------------- ELECTRONICS ----------------
  {
    id: 13,
    name: "iPhone 15",
    category: "electronics",
    subCategory: "Mobiles",
    price: 59999,
    rating: 4.7,
    emoji: "📱",
    stock: true,
  },
  {
    id: 14,
    name: "Samsung Galaxy",
    category: "electronics",
    subCategory: "Mobiles",
    price: 39999,
    rating: 4.5,
    emoji: "📱",
    stock: true,
  },
  {
    id: 15,
    name: "HP Laptop",
    category: "electronics",
    subCategory: "Laptops",
    price: 54999,
    rating: 4.4,
    emoji: "💻",
    stock: true,
  },
  {
    id: 16,
    name: "iPad",
    category: "electronics",
    subCategory: "Tablets",
    price: 42999,
    rating: 4.6,
    emoji: "📲",
    stock: true,
  },
  {
    id: 17,
    name: "Sony Headphones",
    category: "electronics",
    subCategory: "Headphones",
    price: 7999,
    rating: 4.5,
    emoji: "🎧",
    stock: true,
  },
  {
    id: 18,
    name: "Smart Watch",
    category: "electronics",
    subCategory: "Smart Watches",
    price: 2999,
    rating: 4.2,
    emoji: "⌚",
    stock: true,
  },
];

export default products;